version: '3.5'

services:
  antree-order-db:
    container_name: "antree-order-api-ktor"
    image: postgres:12-alpine
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: antree-order
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  pgadmin:
    container_name: "pgadmin4_container"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"